name: llama_3

ckpt_dir: /home/ubuntu/model_weights/Meta-Llama-3-8B-Instruct
tokenizer_path: /home/ubuntu/model_weights/Meta-Llama-3-8B-Instruct/tokenizer.model

max_seq_len: 512
model_parallel_size: 1

global_generation_params:
  temperature: 0
  top_p: 0.9
  logprobs: False
  echo: False
