defaults:
  - model: llama_3
  - coordinator: ray_coordinator
  - prefill_scheduler: fcfs
  - decode_scheduler: fcfs
  - request_generator: shareGPT_uniform_1_rps
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

seed: 1