defaults:
  - model: llama_3
  - coordinator: ray_coordinator
  - prefill_scheduler: srpt
  - decode_scheduler: preemptible_srpt
  - request_generator: shareGPT_1_rps
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

seed: 1