defaults:
  - model: llama_3
  - coordinator: disaggregation_coordinator
  - scheduler: first_come_first_serve
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

seed: 1
