name: preemptible_srpt

batch_size: 8
min_batches_before_preemption: 4
max_batches_before_promotion: 256
max_requests_in_scheduler: 16
scoring_method: estimated_rpt

initial_score: 0
tokens_per_word: 3
fcr_ratio: 2
tokenizer_path: /home/ubuntu/model_weights/Meta-Llama-3-8B-Instruct/tokenizer.model
num_tokens_before_scoring: 16
use_oracle_len: False